### ISSUE TITLE
IP Camera support

### ISSUE THREAD

**Issue by davidfegyver** [davidfegyver/szabadfogasu-maszk#3]

**Comment by davidfegyver** [comment]
Actually this is easy to solve :D (I already did this - manually, so I just have to add a CLI argument to make it work easier)

**Comment by davidfegyver** [comment]
Done in https://github.com/davidfegyver/szabadfogasu-maszk/commit/016c7b10074bdeb67d2612cb67382f27ba9976ae

**Comment by PiciAkk** [comment]
Thanks, @davidfegyver

**Comment by PiciAkk** [comment]
Ooh, I need to write a documentation for this
