### ISSUE TITLE
Alerting system to an operator

### ISSUE THREAD

**Issue by davidfegyver** [davidfegyver/szabadfogasu-maszk#4]

**Comment by PiciAkk** [comment]
@davidfegyver what do you mean? A mobile app, or a command-line interface?

**Comment by PiciAkk** [comment]
Or an email?

**Comment by PiciAkk** [comment]
Ohh, I contacted @davidfegyver in discord, and he says 'e.g. a web interface, that uses sentintervall'

**Comment by PiciAkk** [comment]
so I think I will make a cross-platform React app in my own github profile. [Click here to access](https://github.com/PiciAkk/maszkimum-alert)

**Comment by davidfegyver** [comment]
🤩
